services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kmstore-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_strong_password123!
    ports:
      - "1433:1433"
    volumes:
      - kmstore_mssql_data:/var/opt/mssql

volumes:
  kmstore_mssql_data:
